In [1]:
import pandas as pd

In [5]:
depts = pd.read_csv("data/communes/dept.csv")
depts

    id num             name  region_id                 region_name
0   80  80            Somme         32             Hauts-de-France
1   81  81             Tarn         76                   Occitanie
2   82  82  Tarn-et-Garonne         76                   Occitanie
3   83  83              Var         93  Provence-Alpes-Côte d'Azur
4   84  84         Vaucluse         93  Provence-Alpes-Côte d'Azur
..  ..  ..              ...        ...                         ...
91  49  49   Maine-et-Loire         52            Pays de la Loire
92  50  50           Manche         28                   Normandie
93  51  51            Marne         44                   Grand Est
94  52  52      Haute-Marne         44                   Grand Est
95  53  53          Mayenne         52            Pays de la Loire

[96 rows x 5 columns]

In [7]:
communes = pd.read_csv("data/communes/communes.csv", low_memory=False)
communes

,id,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,...,dept_id,date,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin
0,2439,02439,Les Septvallons,LES SEPTVALLONS,3.674626,49.352746,240200501.0,Communauté de communes du Val de l'Aisne,51250,Fismes,...,2,2025-06-26 23:12:22.934702,NaN,NaN,2016-01-01,NaN,COM,Longueval-Barbonval,LONGUEVAL BARBONVAL,2016-01-01
1,2319,02319,Fonsomme,FONSOMME,3.396855,49.901644,200071892.0,Communauté d'agglomération du Saint-Quentinois,02691,Saint-Quentin,...,2,2025-06-26 23:12:10.400503,NaN,NaN,2011-03-25,NaN,COM,Fonsommes,FONSOMMES,2011-03-25
2,2818,02818,Villiers-Saint-Denis,VILLIERS SAINT DENIS,3.261168,48.997442,240200584.0,Communauté de communes du Canton de Charly-sur...,02163,Charly-sur-Marne,...,2,2025-06-26 23:12:07.373128,NaN,NaN,1970-04-13,NaN,COM,Villiers-sur-Marne,VILLIERS SUR MARNE,1970-04-13
3,1426,01426,Val-Revermont,VAL REVERMONT,5.363443,46.285725,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01072,Ceyzériat,...,1,2025-06-26 23:12:14.270435,NaN,NaN,2016-01-01,NaN,COM,Treffort-Cuisiat,TREFFORT CUISIAT,2016-01-01
4,2220,02220,Coulonges-Cohan,COULONGES COHAN,3.627456,49.198618,200072031.0,Communauté d'agglomération de la Région de Châ...,02305,Fère-en-Tardenois,...,2,2025-06-26 23:12:10.399502,NaN,NaN,1971-01-01,NaN,COM,Coulonges-en-Tardenois,COULONGES EN TARDENOIS,1971-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38656,49183,49183,Val d'Erdre-Auxence,VAL D ERDRE AUXENCE,-0.931389,47.513413,200071868.0,Communauté de communes des Vallées du Haut-Anjou,49054,Candé,...,49,2025-06-26 23:12:06.025741,NaN,NaN,2016-12-15,NaN,COM,Le Louroux-Béconnais,LE LOUROUX BECONNAIS,2016-12-15
38657,51611,51611,Vert-Toulon,VERT TOULON,3.906460,48.847976,200067684.0,"Communauté d''agglomération Épernay,Coteaux et...",51612,Blancs-Coteaux,...,51,2025-06-26 23:12:26.361735,NaN,NaN,1973-09-01,NaN,COM,Vert-la-Gravelle,VERT LA GRAVELLE,1973-09-01
38658,60456,60456,La Neuville-Roy,LA NEUVILLE ROY,2.582093,49.479639,246000566.0,Communauté de communes du Plateau Picard,60223,Estrées-Saint-Denis,...,60,2025-06-26 23:12:47.897825,NaN,NaN,2004-08-30,NaN,COM,Laneuvilleroy,LANEUVILLEROY,2004-08-30
38659,67228,67228,Neugartheim-Ittlenheim,NEUGARTHEIM ITTLENHEIM,7.541469,48.656860,200034635.0,Communauté de communes du Kochersberg,67495,Truchtersheim,...,67,2025-06-26 23:12:33.655919,NaN,NaN,1973-01-01,NaN,COM,Ittlenheim,ITTLENHEIM,1973-01-01
38660,7259,07259,Saint-Just-d'Ardèche,SAINT JUST D ARDECHE,4.624979,44.293723,240700864.0,Communauté de communes du Rhône aux Gorges de ...,30202,Pont-Saint-Esprit,...,7,2025-06-26 23:12:23.023716,NaN,NaN,2011-03-25,NaN,COM,Saint-Just,SAINT JUST,2011-03-25

In [13]:
communes_depts = pd.merge(depts, communes, left_on="id", right_on="dept_id", suffixes=("", "_dept"))
communes_depts

,id,num,name,region_id,region_name,id_dept,code,nom,nom_norm,lon,...,dept_id,date,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin
0,80,80,Somme,32,Hauts-de-France,80245,80245,Domléger-Longvillers,DOMLEGER LONGVILLERS,2.087590,...,80,2025-06-26 23:12:15.517691,NaN,NaN,1972-10-01,NaN,COM,Domléger,DOMLEGER,1972-10-01
1,80,80,Somme,32,Hauts-de-France,80295,80295,Étinehem-Méricourt,ETINEHEM MERICOURT,2.685327,...,80,2025-06-26 23:12:12.63082,NaN,NaN,2017-01-01,NaN,COM,Étinehem,ETINEHEM,2017-01-01
2,80,80,Somme,32,Hauts-de-France,80436,80436,Hescamps,HESCAMPS,1.878108,...,80,2025-06-26 23:12:10.883394,NaN,NaN,1972-11-01,NaN,COM,Hescamps-Saint-Clair,HESCAMPS SAINT CLAIR,1972-11-01
3,80,80,Somme,32,Hauts-de-France,80463,80463,Lamotte-Warfusée,LAMOTTE WARFUSEE,2.591403,...,80,2025-06-26 23:12:21.205588,NaN,NaN,1974-01-01,NaN,COM,Lamotte-en-Santerre,LAMOTTE EN SANTERRE,1974-01-01
4,80,80,Somme,32,Hauts-de-France,80562,80562,Montigny-sur-l'Hallue,MONTIGNY SUR L HALLUE,2.422383,...,80,2025-06-26 23:12:03.009538,NaN,NaN,1956-01-23,NaN,COM,Montigny,MONTIGNY,1956-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38656,53,53,Mayenne,52,Pays de la Loire,53182,53182,Port-Brillet,PORT BRILLET,-0.964161,...,53,2025-06-26 23:12:52.946242,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN
38657,53,53,Mayenne,52,Pays de la Loire,53226,53226,Saint-Hilaire-du-Maine,SAINT HILAIRE DU MAINE,-0.931042,...,53,2025-06-26 23:12:30.762426,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN
38658,53,53,Mayenne,52,Pays de la Loire,53266,53266,Trans,TRANS,-0.308765,...,53,2025-06-26 23:12:06.129584,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN
38659,53,53,Mayenne,52,Pays de la Loire,53185,53185,Pré-en-Pail-Saint-Samson,PRE EN PAIL SAINT SAMSON,-0.194558,...,53,2025-06-26 23:12:42.370645,NaN,NaN,2016-01-01,NaN,COM,Pré-en-Pail,PRE EN PAIL,2016-01-01
38660,53,53,Mayenne,52,Pays de la Loire,53249,53249,Vimartin-sur-Orthe,VIMARTIN SUR ORTHE,-0.218435,...,53,2025-06-26 23:11:59.620812,NaN,NaN,2021-01-01,NaN,COM,Saint-Pierre-sur-Orthe,SAINT PIERRE SUR ORTHE,2021-01-01

In [9]:
cps = pd.read_csv("data/communes/cp.csv")
cps

       code_postal code_insee
0             1000      01053
1             1000      01344
2             1090      01165
3             1090      01169
4             1090      01183
...            ...        ...
35397        95840      95678
35398        95850      95316
35399        95850      95365
35400        95870      95063
35401        95880      95210

[35402 rows x 2 columns]

In [14]:
communes_depts_cps = pd.merge(communes_depts, cps, left_on="code", right_on="code_insee", suffixes=("", "_cp"))
communes_depts_cps

,id,num,name,region_id,region_name,id_dept,code,nom,nom_norm,lon,...,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin,code_postal,code_insee
0,80,80,Somme,32,Hauts-de-France,80245,80245,Domléger-Longvillers,DOMLEGER LONGVILLERS,2.087590,...,NaN,NaN,1972-10-01,NaN,COM,Domléger,DOMLEGER,1972-10-01,80370,80245
1,80,80,Somme,32,Hauts-de-France,80295,80295,Étinehem-Méricourt,ETINEHEM MERICOURT,2.685327,...,NaN,NaN,2017-01-01,NaN,COM,Étinehem,ETINEHEM,2017-01-01,80340,80295
2,80,80,Somme,32,Hauts-de-France,80436,80436,Hescamps,HESCAMPS,1.878108,...,NaN,NaN,1972-11-01,NaN,COM,Hescamps-Saint-Clair,HESCAMPS SAINT CLAIR,1972-11-01,80290,80436
3,80,80,Somme,32,Hauts-de-France,80463,80463,Lamotte-Warfusée,LAMOTTE WARFUSEE,2.591403,...,NaN,NaN,1974-01-01,NaN,COM,Lamotte-en-Santerre,LAMOTTE EN SANTERRE,1974-01-01,80800,80463
4,80,80,Somme,32,Hauts-de-France,80562,80562,Montigny-sur-l'Hallue,MONTIGNY SUR L HALLUE,2.422383,...,NaN,NaN,1956-01-23,NaN,COM,Montigny,MONTIGNY,1956-01-23,80260,80562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35397,53,53,Mayenne,52,Pays de la Loire,53182,53182,Port-Brillet,PORT BRILLET,-0.964161,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,53410,53182
35398,53,53,Mayenne,52,Pays de la Loire,53226,53226,Saint-Hilaire-du-Maine,SAINT HILAIRE DU MAINE,-0.931042,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,53380,53226
35399,53,53,Mayenne,52,Pays de la Loire,53266,53266,Trans,TRANS,-0.308765,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,53160,53266
35400,53,53,Mayenne,52,Pays de la Loire,53185,53185,Pré-en-Pail-Saint-Samson,PRE EN PAIL SAINT SAMSON,-0.194558,...,NaN,NaN,2016-01-01,NaN,COM,Pré-en-Pail,PRE EN PAIL,2016-01-01,53140,53185
35401,53,53,Mayenne,52,Pays de la Loire,53249,53249,Vimartin-sur-Orthe,VIMARTIN SUR ORTHE,-0.218435,...,NaN,NaN,2021-01-01,NaN,COM,Saint-Pierre-sur-Orthe,SAINT PIERRE SUR ORTHE,2021-01-01,53160,53249

In [12]:
communes_depts_cps[communes_depts_cps["code"]=="38185"]

,id,num,name,region_id,region_name,id_right,code,nom,nom_norm,lon,...,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin,code_postal,code_insee
24423,38,38,Isère,84,Auvergne-Rhône-Alpes,38185,38185,Grenoble,GRENOBLE,5.72487,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,38000,38185
24424,38,38,Isère,84,Auvergne-Rhône-Alpes,38185,38185,Grenoble,GRENOBLE,5.72487,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,38100,38185
24425,38,38,Isère,84,Auvergne-Rhône-Alpes,38185,38185,Grenoble,GRENOBLE,5.72487,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,38700,38185

In [17]:
communes_depts_cps[communes_depts_cps["code_postal"]==38250]

,id,num,name,region_id,region_name,id_dept,code,nom,nom_norm,lon,...,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin,code_postal,code_insee
24224,38,38,Isère,84,Auvergne-Rhône-Alpes,38205,38205,Lans-en-Vercors,LANS EN VERCORS,5.590175,...,NaN,NaN,1947-05-09,NaN,COM,Lans,LANS,1947-05-09,38250,38205
24609,38,38,Isère,84,Auvergne-Rhône-Alpes,38433,38433,Saint-Nizier-du-Moucherotte,SAINT NIZIER DU MOUCHEROTTE,5.631374,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,38250,38433
24694,38,38,Isère,84,Auvergne-Rhône-Alpes,38548,38548,Villard-de-Lans,VILLARD DE LANS,5.543917,...,NaN,NaN,1943-01-01,NaN,NaN,NaN,NaN,NaN,38250,38548
24728,38,38,Isère,84,Auvergne-Rhône-Alpes,38129,38129,Corrençon-en-Vercors,CORRENCON EN VERCORS,5.517578,...,NaN,NaN,1952-06-18,NaN,COM,Corrençon,CORRENCON,1952-06-18,38250,38129