In [1]:
import pandas as pd
import sklearn.neighbors as n
import matplotlib.pyplot as plt
import sklearn.model_selection as ms
import sklearn.preprocessing as pp
import numpy as np

In [2]:
df = pd.read_csv("data/heartdisease/data_cleaned_up.csv")
df.head(10)

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  num
0   28    1   2       130   132    0        2      185      0      0.0    0
1   29    1   2       120   243    0        0      160      0      0.0    0
2   30    0   1       170   237    0        1      170      0      0.0    0
3   31    0   2       100   219    0        1      150      0      0.0    0
4   32    0   2       105   198    0        0      165      0      0.0    0
5   32    1   2       110   225    0        0      184      0      0.0    0
6   32    1   2       125   254    0        0      155      0      0.0    0
7   33    1   3       120   298    0        0      185      0      0.0    0
8   34    0   2       130   161    0        0      190      0      0.0    0
9   34    1   2       150   214    0        1      168      0      0.0    0

In [3]:
x = df.drop("num", axis=1)
y = df["num"]
xtrain, xtest, ytrain, ytest = ms.train_test_split(x,y,train_size=0.8, test_size=0.2)

In [7]:
# scaler = pp.MinMaxScaler()
# scaler = pp.StandardScaler()
scaler = pp.RobustScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)
test = pd.DataFrame(xtrain)
test

,0,1,2,3,4,5,6,7,8,9
0,0.000000,0.0,0.5,-0.40,0.483660,3.991154,2.060315,0.303030,1.0,2.0
1,-0.408163,-1.0,-0.5,-0.50,0.366013,0.000000,0.000000,-0.666667,0.0,0.0
2,0.489796,-1.0,-0.5,1.00,-0.104575,0.000000,0.000000,-0.303030,0.0,0.0
3,0.816327,0.0,0.5,0.25,-0.209150,0.000000,0.000000,-1.212121,0.0,0.0
4,0.816327,-1.0,-0.5,2.50,2.026144,0.000000,0.000000,-0.909091,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
203,0.489796,-1.0,0.0,0.00,0.732026,0.000000,2.060315,-1.212121,1.0,0.0
204,-0.081633,-1.0,-0.5,0.50,0.248366,0.000000,0.000000,-0.151515,0.0,1.0
205,-0.081633,-1.0,0.5,-0.50,-0.431373,0.000000,0.000000,-1.272727,1.0,2.0
206,0.408163,0.0,0.5,-0.50,0.104575,0.000000,0.000000,-0.727273,1.0,0.0
207,0.653061,0.0,0.5,1.25,1.359477,3.991154,0.000000,0.303030,1.0,3.0

In [8]:
for k in range(3,15):
    model = n.KNeighborsClassifier(n_neighbors=k)
    model.fit(xtrain, ytrain)
    print(k, model.score(xtest, ytest))

3 0.8269230769230769
4 0.7884615384615384
5 0.8076923076923077
6 0.8076923076923077
7 0.8269230769230769
8 0.8076923076923077
9 0.7884615384615384
10 0.7884615384615384
11 0.8076923076923077
12 0.7884615384615384
13 0.7884615384615384
14 0.7884615384615384