In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data/communes/dept.csv", index_col="id")
df

   num             name  region_id                 region_name
id
80  80            Somme         32             Hauts-de-France
81  81             Tarn         76                   Occitanie
82  82  Tarn-et-Garonne         76                   Occitanie
83  83              Var         93  Provence-Alpes-Côte d'Azur
84  84         Vaucluse         93  Provence-Alpes-Côte d'Azur
..  ..              ...        ...                         ...
49  49   Maine-et-Loire         52            Pays de la Loire
50  50           Manche         28                   Normandie
51  51            Marne         44                   Grand Est
52  52      Haute-Marne         44                   Grand Est
53  53          Mayenne         52            Pays de la Loire

[96 rows x 4 columns]

In [4]:
df.describe()

       region_id
count  96.000000
mean   55.229167
std    26.638508
min    11.000000
25%    28.000000
50%    53.000000
75%    76.000000
max    94.000000