In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [12]:
df = pd.read_csv("data/heartdisease/data_with_nan.csv", na_values=".")
# df.dtypes
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,NaN,NaN,NaN,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,NaN,NaN,NaN,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.0,0.0,0.0,94.0,1.0,2.5,NaN,NaN,NaN,1
290,54,0,3,130.0,294.0,0.0,1.0,100.0,1.0,0.0,2.0,NaN,NaN,1
291,56,1,4,155.0,342.0,1.0,0.0,150.0,1.0,3.0,2.0,NaN,NaN,1
292,58,0,2,180.0,393.0,0.0,0.0,110.0,1.0,1.0,2.0,NaN,7.0,1
293,65,1,4,130.0,275.0,0.0,1.0,115.0,1.0,1.0,2.0,NaN,NaN,1

In [13]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      1
chol         23
fbs           8
restecg       1
thalach       1
exang         1
oldpeak       0
slope       190
ca          291
thal        266
num           0
dtype: int64

In [14]:
# Pour slope, ca & thal droper les colonnes
# Pour chol créer une fonction qui créer mean + std * (rnd - 0.5) * 2 et l'appliquer avec la fonction apply
# .apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
# Pour trestbps, restecg, thalach & exang & fbs droper les lignes avec dropna

In [15]:
df = df.drop(["slope", "ca", "thal"], axis=1)
df

     age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  num
0     28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0    0
1     29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0    0
2     29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0    0
3     30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0    0
4     31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0    0
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...  ...
289   52    1   4     160.0  331.0  0.0      0.0     94.0    1.0      2.5    1
290   54    0   3     130.0  294.0  0.0      1.0    100.0    1.0      0.0    1
291   56    1   4     155.0  342.0  1.0      0.0    150.0    1.0      3.0    1
292   58    0   2     180.0  393.0  0.0      0.0    110.0    1.0      1.0    1
293   65    1   4     130.0  275.0  0.0      1.0    115.0    1.0      1.0    1

[294 rows x 11 columns]

In [20]:
chol_mean = df["chol"].mean()
chol_std = df["chol"].std()
df["chol"] = df["chol"].apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,246.054261,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1
293,65,1,4,130.0,275.000000,0.0,1.0,115.0,1.0,1.0,1

In [22]:
df = df.dropna()
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,246.054261,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1
293,65,1,4,130.0,275.000000,0.0,1.0,115.0,1.0,1.0,1

In [24]:
df.to_csv("data/heartdisease/dataclean.csv", index=None)

In [25]:
ok = df[df["num"]==0]
ko = df[df["num"]==1]
ok.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
count,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.0
mean,46.806630,0.646409,2.618785,130.795580,238.968343,0.038674,0.220994,145.348066,0.104972,0.206077,0.0
std,7.913502,0.479410,0.865050,16.853196,51.988411,0.193352,0.478192,22.230993,0.307368,0.522831,0.0
min,28.000000,0.000000,1.000000,98.000000,85.000000,0.000000,0.000000,90.000000,0.000000,0.000000,0.0
25%,41.000000,0.000000,2.000000,120.000000,207.000000,0.000000,0.000000,130.000000,0.000000,0.000000,0.0
50%,48.000000,1.000000,2.000000,130.000000,230.493121,0.000000,0.000000,145.000000,0.000000,0.000000,0.0
75%,54.000000,1.000000,3.000000,140.000000,273.000000,0.000000,0.000000,160.000000,0.000000,0.000000,0.0
max,62.000000,1.000000,4.000000,190.000000,412.000000,1.000000,2.000000,190.000000,1.000000,3.000000,0.0

In [26]:
ko.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.0
mean,49.601942,0.883495,3.650485,136.116505,264.636652,0.126214,0.203883,128.378641,0.660194,1.262136,1.0
std,7.477207,0.322398,0.750278,18.863961,77.638339,0.333714,0.428386,22.794098,0.475959,1.061456,0.0
min,31.000000,0.000000,1.000000,92.000000,117.000000,0.000000,0.000000,82.000000,0.000000,0.000000,1.0
25%,46.000000,1.000000,4.000000,120.000000,214.425215,0.000000,0.000000,113.500000,0.000000,0.000000,1.0
50%,50.000000,1.000000,4.000000,135.000000,257.000000,0.000000,0.000000,126.000000,1.000000,1.000000,1.0
75%,54.000000,1.000000,4.000000,150.000000,288.500000,0.000000,0.000000,147.500000,1.000000,2.000000,1.0
max,66.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,180.000000,1.000000,5.000000,1.0