In [11]:
import pandas as pd
import numpy as np
import sklearn.neighbors as n
import sklearn.model_selection as ms
import sklearn.preprocessing as pp

In [4]:
df = pd.read_csv("data/absenteeism_at_work/absence_cat.csv", delimiter=",")
df.head(10)

,Unnamed: 0,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,...,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours,absence_category
0,0,11,26,7,3,1,289,36,13,33,...,1,2,1,0,1,90,172,30,4,1
1,1,36,0,7,3,1,118,13,18,50,...,1,1,1,0,0,98,178,31,0,0
2,2,3,23,7,4,1,179,51,18,38,...,1,0,1,0,0,89,170,31,2,1
3,3,7,7,7,5,1,279,5,14,39,...,1,2,1,1,0,68,168,24,4,1
4,4,11,23,7,5,1,289,36,13,33,...,1,2,1,0,1,90,172,30,2,1
5,5,3,23,7,6,1,179,51,18,38,...,1,0,1,0,0,89,170,31,2,1
6,6,10,22,7,6,1,361,52,3,28,...,1,1,1,0,4,80,172,27,8,2
7,7,20,23,7,6,1,260,50,11,36,...,1,4,1,0,0,65,168,23,4,1
8,8,14,19,7,2,1,155,12,14,34,...,1,2,1,0,0,95,196,25,40,4
9,9,1,22,7,2,1,235,11,14,37,...,3,1,0,0,1,88,172,29,8,2

In [6]:
y = df["absence_category"]
x = df.drop(["absence_category", "absenteeism_time_in_hours", "id"], axis=1)

In [ ]:
# Train test split
# modèle knn avec k = 3
# score
# tester toutes les valeurs de k entre 3 et 15

In [9]:
xtrain, xtest, ytrain, ytest = ms.train_test_split(x,y,train_size=0.8, test_size=0.2)

In [12]:
# scaler = pp.MinMaxScaler()
# scaler = pp.StandardScaler()
scaler = pp.RobustScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)
test = pd.DataFrame(xtrain)
test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-0.157104,0.384615,0.571429,-0.5,0.5,-1.320988,-0.390977,0.714286,1.444444,0.016799,-1.75,0.0,0.0,0.0,0.0,0.0,0.0,0.75,2.333333,0.857143
1,-0.695355,-0.076923,0.857143,0.0,0.5,1.679012,0.781955,-1.428571,-1.000000,-0.064373,0.50,0.0,0.0,0.0,0.0,0.0,4.0,-0.15,0.333333,0.285714
2,0.378415,0.000000,0.428571,-1.0,-1.0,-0.567901,0.751880,0.714286,0.111111,-0.054530,-2.00,0.0,0.0,-0.5,0.0,0.0,0.0,0.30,-0.333333,0.857143
3,0.214481,0.384615,0.000000,-1.0,0.0,-0.567901,0.751880,0.714286,0.111111,-0.225119,0.00,0.0,0.0,-0.5,0.0,0.0,0.0,0.30,-0.333333,0.857143
4,0.025956,0.384615,-0.571429,1.0,-0.5,0.432099,0.721805,-0.285714,-0.111111,-0.271906,0.25,0.0,0.0,1.5,0.0,0.0,0.0,-0.90,-1.000000,-0.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,0.550546,-0.769231,0.857143,-0.5,0.5,-0.567901,0.000000,-0.571429,-0.777778,0.356534,0.75,0.0,2.0,-0.5,-1.0,0.0,0.0,-1.35,0.000000,-0.857143
588,0.001366,-1.538462,-0.714286,0.0,-0.5,0.814815,0.150376,-0.142857,0.333333,1.439521,1.25,0.0,0.0,0.0,0.0,0.0,1.0,-0.50,0.000000,0.000000
589,0.804645,-0.769231,-0.285714,0.5,0.0,-0.444444,0.090226,0.000000,-0.444444,-0.392865,-1.00,0.0,0.0,0.5,-1.0,0.0,2.0,-0.70,-1.333333,0.000000
590,0.050546,0.000000,-0.571429,-0.5,-0.5,0.259259,-0.030075,0.428571,0.444444,-0.271906,0.25,0.0,0.0,-0.5,0.0,0.0,0.0,-0.80,-0.333333,-0.285714
591,-0.072404,-1.769231,0.714286,-0.5,0.5,0.666667,-0.631579,0.142857,0.222222,0.432696,0.50,1.0,0.0,0.5,0.0,1.0,0.0,-0.75,-1.000000,-0.142857

In [13]:
for k in range(3,15):
    model = n.KNeighborsClassifier(n_neighbors=k)
    model.fit(xtrain, ytrain)
    print(k, model.score(xtest, ytest))

3 0.7094594594594594
4 0.6891891891891891
5 0.7162162162162162
6 0.7162162162162162
7 0.7364864864864865
8 0.7094594594594594
9 0.7364864864864865
10 0.6959459459459459
11 0.7027027027027027
12 0.6824324324324325
13 0.6959459459459459
14 0.6824324324324325